### PR TITLE
feat: Manage service

### PR DESCRIPTION
**Pull request by deimosfr**
Hi,

To avoid issues with systemd and docker when building an image, I added service management.

Can you please merge and create a new version?

Thanks

### CODE REVIEW

**Comment by jdauphant** [comment]
Hi @deimosfr ,

Thanks for the pull request.
Do you use this role : 
- inside a docker to install nginx and manage configuration inside the docker (you can use nginx_daemon_mode: False normally in this case )
or
- outside the docker to manage the configuration of the nginx container from the host (you can use nginx_installation_type: "docker" in this case)
Or a another case ?

**Comment by deimosfr** [comment]
Hi,

I use this role inside and ouside Docker. Outside Docker, I do not encounter issues, however inside, using Debian Jessie and the Ansible "service" module, I get this kind of issues:
```
    docker: TASK: [jdauphant.nginx | Start the nginx service] *****************************
    docker: <127.0.0.1> REMOTE_MODULE service name=nginx state=started enabled=yes
    docker: <127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1427783859.53-173612273946507 && echo $HOME/.ansible/tmp/ansible-tmp-1427783859.53-173612273946507']
    docker: <127.0.0.1> PUT /tmp/tmpvgFfoK TO /root/.ansible/tmp/ansible-tmp-1427783859.53-173612273946507/service
    docker: <127.0.0.1> EXEC ['/bin/sh', '-c', u'LANG=C LC_CTYPE=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1427783859.53-173612273946507/service; rm -rf /root/.ansible/tmp/ansible-tmp-1427783859.53-173612273946507/ >/dev/null 2>&1']
    docker: failed: [127.0.0.1] => {"cmd": "/sbin/initctl status nginx", "failed": true, "rc": 8}
    docker: msg: [Errno 8] Exec format error
```
When I manually run it, I get:
```
/sbin/initctl status nginx ; echo $? 
101
```

May be you got a better proposition...?

Thanks

**Comment by deimosfr** [comment]
After a long discussion on IRC with several guys, it looks like with Docker, it's recommended to not mange the service at all.

Please merge this PR.

**Comment by jdauphant** [comment]
Hi @deimosfr ,

Sorry for the delay of my answer.
Normally "nginx_daemon_mode: False" cover you case, can you confirm ?

Best regards,
Julien

**Comment by deimosfr** [comment]
Hi @jdauphant,

This is in fact not the same thing. You may want the service to run as daemon but just do not want ansible to manage it.

This is my case here.

**Comment by jdauphant** [comment]
It's strange because nginx should not be running in daemon mode inside a docker container.

It's the case for the official image : 
https://github.com/nginxinc/docker-nginx/blob/master/Dockerfile
And also the dockerfile version :
https://github.com/dockerfile/nginx/blob/master/Dockerfile

**Comment by deimosfr** [comment]
It looks like you're right. It works with that configuration.

Thanks

**Comment by deimosfr** [comment]
Hi,

I say it too quickly :-/, can you please reopen the case. Here is a way to reproduce the issue, I've a configuration with:
```
nginx_daemon_mode: 'off'
```
When I run the Ansible role, I still got that issue:
```
TASK: [jdauphant.nginx | Copy the nginx configuration file] ******************* 
--- before
+++ after
@@ -1,11 +1,11 @@
-#Ansible managed: modified on 2015-04-11 23:21:17 by root on e78444ad0488
+#Ansible managed: modified on 2015-03-12 23:46:01 by pmavro on deb-pmavro
 user              www-data;
 
 worker_processes  8;
 pid        /var/run/nginx.pid;
 worker_rlimit_nofile 8192;
 
 events {
     worker_connections  8192;
 }
 
@@ -41,10 +41,11 @@
         gzip_proxied any;
         gzip_buffers 4 128k;
         gzip_comp_level 6;
         gzip_http_version 1.1;
         gzip_types text/plain text/css application/x-javascript application/javascript text/xml application/xml+rss text/psajs text/javascript;
 
         include /etc/nginx/conf.d/*.conf;
         include /etc/nginx/sites-enabled/*;
 }
 
+daemon off;

changed: [10.0.0.68]

[...]

TASK: [jdauphant.nginx | Start the nginx service] ***************************** 
failed: [10.0.0.68] => {"cmd": "/sbin/initctl status nginx", "failed": true, "rc": 8}
msg: [Errno 8] Exec format error

FATAL: all hosts have already failed -- aborting
```
The PR I've made permit to not manage the service management and avoid this kind of issue.

For information, the Docker base is Debian Jessie from official repo and I'm pretty sure we're going to have more and more this kind of issue with Systemd in the future.

So the daemon mode and the service management is 2 different things. Please reconsider the merging of this pull request.

**Comment by jdauphant** [comment]
HI,

It's a bug corrected in v1.3.3 service and handler should not be run with "nginx_daemon_mode" == "off".
Do you still have the problem ?

**Comment by deimosfr** [comment]
1.3.3 updated 2 days ago :-p, it works thanks !

**Pull request closed without merging**
