### PR TITLE
Add support from FreeBSD port installation (compile source) rather then package

### PR DESCRIPTION
**Pull request by mike-pt**
I'm not sure if this is the best way, so fell free to reject it, but I think this way we could use the instaltion.source.yml task to add other systems.

My main goal here however was FreeBSD and this is a 1st step, ideally a template for "make options" should be added so we can decide what to compile.

NOTES: this adds --> `nginx_freebsd_port` var with default "www/nginx" in case we want to use "www/nginx-devel" 
Also, and this is the part I'm not sure if its the best way...  but I've reused `nginx_installation_type` so in case he set it to `"source"` we would run the instaltion.source task...

### CODE REVIEW

**Comment by jdauphant** [comment]
Thanks, it's the good way.
I will have preferred "sources" instead of "source" (to have the convention has "packages").
You have to update nginx_installation_types_using_service: ["packages", "configuration-only"] in vars/main.yml also service will be unmanaged
Tests fail be it seen unrelated to your changes

**Comment by jdauphant** [comment]
@mike-pt Don't hesitate to ask if you have questions

**Comment by mike-pt** [comment]
Sorry just didn't have time to review this, I'll try to have a look during the weekend and make the required fixes to the PR, and if possible add the "options" template.

I was thinking on how to do it... but probably the best ways is to use the file generated by make config

**Comment by jdauphant** [comment]
@mike-pt I will let you reopen the PR if you want to work on it

**Pull request closed without merging**
