### PR TITLE
use with_dict instead of accessing keys from dict.keys() (#150)

### PR DESCRIPTION
**Pull request by tyxieblub**

### CODE REVIEW

**Comment by jdauphant** [comment]
Kudos for the work @tyxieblub !

**Comment by jdauphant** [comment]
@flatrocks take care of this change in your custom templates if you update to v2.7:

> it may pose a problem for people with custom templates using these variables as they cannot access them with nginx_sites[item].var anymore and should now use item.value.var

**Comment by flatrocks** [comment]
@jdauphant Thanks for the heads-up!
Urgent for me to get busy on that pull request for adding because also the readme Example 9 (custom templates) is incorrect, too!

**Comment by jdauphant** [comment]
@flatrocks Oh, thanks, I just fixed the readme.

**Comment by flatrocks** [comment]
My apologies for not getting to this sooner.  I just posted pull request #155 to provide testing for custom templates, and further updated README to match the test.

**Pull request merged**
