### PR TITLE
add nginx_remove_default flag to disable default site

### PR DESCRIPTION
**Pull request by aisch**
wanted to remove *default* site but keep unmanaged sites (so don't want to enable `keep_only_specified`).

### CODE REVIEW

**Comment by aisch** [comment]
btw shouldn't `keep_only_specified` be `nginx_keep_only_specified`? probably breaking change to prefix it now.

**Comment by jdauphant** [comment]
The default behavior is already "remove default site but keep unmanaged sites" (with the keep_only_specified is default to False).
Do you incur a problem with that ?

Also, you have right for "keep_only_specified", it was keep for compatibility, you can rename it and do something like : 
nginx_keep_only_specified: "{{keep_only_specified | default(False)}}"

**Comment by aisch** [comment]
ic, i should be as you say. maybe i was using an old version. i'll try with latest and close this pr. thanks!

**Comment by aisch** [comment]
so it does rm `/etc/nginx/sites-enabled/default` but enables `default.conf` w/ `/etc/nginx/sites-enabled/default.conf`. i tried clearing `nginx_sites: {}` but it was still enabling it. 

doing this disables `default.conf`:
```yaml
nginx_remove_sites: [default]
```

so no need to add this new var.

**Pull request closed without merging**
