### PR TITLE
Add correct EPEL repo for CentOS/RHEL 7

### PR DESCRIPTION
**Pull request by etcet**
yum install epel-release instead of copying the EL6 repo file when ansible_distribution_major_version|int >= 7

### CODE REVIEW

**Comment by jdauphant** [comment]
Thanks for the pull request.

Hey @jrobeson can you confirm this looks ok for CentOS/RHEL 7 ?
Thanks in advance for your answer

**Comment by jrobeson** [comment]
i never relied on this feature, i already used my own rpm due to required custom build options. According to this page though, epel release is available for 6 too, so it seems like we should always use it: https://fedoraproject.org/wiki/EPEL

**Comment by jdauphant** [comment]
I see the problem :
The EPEL template is specific to EL6
- https://github.com/jdauphant/ansible-role-nginx/blob/master/templates/epel.repo.j2

We should etheir : 
- Correct the template so It could work with EL7
- See if the solution of @etcet works for EL6 (and add a cleanup for the old solution if it's the case)

**Comment by etcet** [comment]
I've confirmed that epel-release is available on CentOS 6:

===================
root@host [60 07:30:40 ~]# cat /etc/redhat-release 
CentOS release 6.6 (Final)
root@host [61 07:33:45 ~]# yum info epel-release
...
Available Packages
Name        : epel-release
Arch        : noarch
Version     : 6
Release     : 8
Size        : 14 k
Repo        : extras
Summary     : Extra Packages for Enterprise Linux repository configuration
URL         : http://dl.fedoraproject.org/pub/epel/
License     : GPLv2
Description : This package contains the Extra Packages for Enterprise Linux (EPEL) repository
            : GPG key as well as configuration for yum and up2date.
===================

I think using the epel-release package is the cleanest solution and I'll submit another pull request later today if nobody objects.

**Comment by jdauphant** [comment]
Ok thanks @etcet

**Comment by etcet** [comment]
OK, should be good to go! I ended up having to roll my own rpm as well but it'll stop anyone else from unwittingly installing packages for CentOS 6 on CentOS 7 :+1:

**Comment by jdauphant** [comment]
Hello and sorry @etcet , I have miss the change in the pull request :(

Thanks for the work :+1:

**Pull request merged**
