### PR TITLE
Upgrade to ansible 2.4

### PR DESCRIPTION
**Pull request by rhpvorderman**
#186

### CODE REVIEW

**Comment by jdauphant** [comment]
@rhpvorderman Thanks, the PR is very good. You have sense of details, I love that ;)

I was thinking maybe we can wait the release of Ansible 2.5 before merging it so the project version will cover both version (I have seen some problems previously where people have to use previous version because of bugs or missing feature).
What do you thing?

**Comment by rhpvorderman** [comment]
Sure. No need to rush the upgrade. Most people will not have updated their ansible yet. And `include:` still works. This pull request only fixes a deprecation warning on 2.4 and later.
It is all up to you when you want to get rid of those warnings ;-).

**Comment by evaryont** [comment]
Ansible 2.5 has been released, time to merge this?

**Comment by jdauphant** [comment]
@evaryont Yep !

**Pull request merged**
