### PR TITLE
Allow access rules to include in site configs

### PR DESCRIPTION
**Pull request by mightydok**
Hello.
I want to add support for custom access config files, like:
```
allow from 123.123.123.123
deny from all
```
I cant use nginx_configs section, because this type of config will be autoloaded at nginx restart and can broke access to web server, so i think i must add another section like nginx_auth_basic_files. 
I change role, README and travis files.

### CODE REVIEW

**Comment by jdauphant** [comment]
Hello @mightydok ,
Thanks for the pull request.
I am more in flavor to use ansible templating.
You have examples here:
https://github.com/jdauphant/ansible-role-nginx/releases/tag/v1.2
and more details here : https://github.com/jdauphant/ansible-role-nginx/pull/33

What do you think ?

Julien

**Comment by mightydok** [comment]
Hello @jdauphant i think we need update README for that info. I will close pull request.

**Comment by jdauphant** [comment]
Yes, an update for the README cool be nice, we need to find good examples for that.

**Comment by mightydok** [comment]
@jdauphant i think example with access rule, with just simple allow all; will suit.

**Pull request closed without merging**
