### PR TITLE
Adding support for comment in site config file

### PR DESCRIPTION
**Pull request by fvahid**
For Adding comment in Nginx config file (site.conf) we need change in following file
site.config.j2
just for showing test I changed defaults/main.yml file

### CODE REVIEW

**Comment by jdauphant** [comment]
@fvahid 
Have you tested directely use YAML syntax ?
Like that :
```
nginx_sites:
￼	  default:
￼	    - "#just show comment in site config file"
            - '#another comment'
￼	    - listen 80 default_server
￼	    - server_name _
￼	    - root "{{ nginx_sites_default_root }}"
```

**Comment by fvahid** [comment]
> @fvahid
> Have you tested directely use YAML syntax ?
> Like that :
> 
> ```
> nginx_sites:
> ￼	  default:
> ￼	    - "#just show comment in site config file"
>             - '#another comment'
> ￼	    - listen 80 default_server
> ￼	    - server_name _
> ￼	    - root "{{ nginx_sites_default_root }}"
> ```

No I use this one in defaults/main.yml file
nginx_sites:
  default:
    - ansible_comment just show comment in site config file
    - listen 80 default_server
    - server_name _
    - root "{{ nginx_sites_default_root }}"
    - index index.html

after that this line 
"# just show comment in site config file"
commented in site.conf file

**Comment by fvahid** [comment]
Here is another result by ansible play 

#
# Ansible managed
#

server {
   listen 443 ssl http2;
   #comment by vahid fardi for describe job;
   listen [::]:443 ssl http2;
   server_name _;
    access_log /var/log/nginx/catchall-access.log netdata;
   error_log /var/log/nginx/catchall-error.log error;
}

**Comment by fvahid** [comment]
@jdauphant please update this issue
Thanks

**Comment by jdauphant** [comment]
Have you try if it's work like that without modification ?
```
nginx_sites:
￼	  default:
￼	    - "#just show comment in site config file"
            - '#another comment'
￼	    - listen 80 default_server
￼	    - server_name _
￼	    - root "{{ nginx_sites_default_root }}"
```
Or with the new notation :
```
nginx_sites:
 hhvm_test:
     - |
       listen 80; 
       # My comment
       server_name test_hhvm.example.com;
       root "/homestead/";
       {{include_nginx_hhvm}}
```
If it's already working in one of this syntax, it's better to use it and we can document for everybody

**Comment by fvahid** [comment]
Dear @jdauphant 

I appreciate you recommendation but in point of my view is better use another variable to fix this issue.

Thansk

**Comment by jdauphant** [comment]
I prefer that we use and document things that already exist ;)

**Pull request closed without merging**
