### PR TITLE
Change depricated 'always_run: yes' to new 'check_mode: no'

### PR DESCRIPTION
**Pull request by luvs**
always_run will be removed in version 2.4.

### CODE REVIEW

**Comment by jdauphant** [comment]
Hello @luvs,
Thanks for the PR.
This change the compatibility, when check_mode have been introduced in Ansible ?

**Comment by luvs** [comment]
Hello @jdauphant,
This is new feature, it was [introduced in 2.2](http://docs.ansible.com/ansible/playbooks_checkmode.html#enabling-or-disabling-check-mode-for-tasks).

Yes you are right may be a bit early to do this change, it breaks compatibility.

**Comment by jdauphant** [comment]
Yep, let's keep that for later maybe when the 2.3 will be available.

**Comment by EdwardPrentice** [comment]
+1

**Comment by andymcc** [comment]
Ansible 2.3 is out now - could we reassess whether this patch can merge now? It's causing ansible-lint failures at the moment.

**Comment by evrardjp** [comment]
We'll probably need to bump the min version to 2.2

**Comment by jdauphant** [comment]
@andymcc Yep
@evrardjp I will do it also

Thanks :)

**Pull request merged**
