### PR TITLE
Add a README example with YAML magic for multiline strings

### PR DESCRIPTION
**Pull request by wkielas**
This adds another example to the README which uses multiline strings. 

I've spent some time searching how to achieve this for my long Nginx location blocks, so it could be helpful for others.

### CODE REVIEW

**Comment by jdauphant** [comment]
Oh thanks, I discover this new yaml, what's the difference with "|" ?
```
 nginx_sites:
        foo:
           - listen 443 ssl
           - server_name foo.example.com
           - set $myhost foo.example.com
           - |
             location / {
               proxy_set_header Host foo.example.com;
             }
          - |
             location ~ /v2/users/.+?/organizations {
               if ($request_method = PUT) {
                 set $myhost bar.example.com;
               }
               if ($request_method = DELETE) {
                 set $myhost bar.example.com;
               }
               proxy_set_header Host $myhost;
             }
```

**Comment by wkielas** [comment]
It's pretty well explained [here](http://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines). 

I used the `>` notation because it's the first one I've found and it looks okay in the config files.

**Comment by jdauphant** [comment]
I prefer recommends  "|" , we will have better file output (it's well managed by the role, it's explain here : https://github.com/jdauphant/ansible-role-nginx/releases/tag/v1.2 ).
Is that ok for you to change it ?

**Comment by wkielas** [comment]
Sure, changed.

**Comment by jdauphant** [comment]
@wkielas Thanks !

**Pull request merged**
