### PR TITLE
Add support to declare nginx modules in config file

### PR DESCRIPTION
**Pull request by q2digger**
Dear Julien,
I have added few changes to your project "ansible-role-nginx" and add support to declare modules. 
My example playbook : 

```yaml
- hosts: all
  roles:
    - role: ansible-role-nginx
      nginx_http_params:
        - sendfile on
        - access_log /var/log/nginx/access.log
        - error_log /var/log/nginx/error.log
        - include snippets/geoip.conf
     nginx_module_configs:
        - ngx_http_geoip_module
      nginx_snippets:
        geoip:
          -    geoip_country /usr/share/GeoIP/GeoIP.dat;
                map $geoip_country_code $allowed_country {
                default yes;
                IR no;
                CN no;
            }
```
And next I just add geoip functions into virtual hosts. 

Thanks,
Dmitry

### CODE REVIEW

**Comment by jdauphant** [comment]
@q2digger I just merged but I just see that there is no documentation for this feature, it will be better to add one.

**Comment by edmachine** [comment]
I just did an ansible run against my server and got an error from this update:
```TASK [jdauphant.nginx : Create configuration for modules] **********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
fatal: [10.129.8.146]: FAILED! => {"failed": true, "msg": "Unexpected failure in finding the lookup named '{{ nginx_module_configs }}' in the available lookup plugins"}
```
do we need to add a default to our configuration files?

**Comment by jdauphant** [comment]
@edelans looks like a bug :( which version of ansible do you have? 
@q2digger do you have an idea?

**Comment by q2digger** [comment]
Hi,
I performed few tests in clear CentOS7 (in Vagrant). I tried run small
playbook from README.md (example 1) and my own playbook - both were
deployed successfully.

P.S. I found another issue with my code (template declares library in
incorrect folder) and I need few days to fix it.

regards,
Dmitry

**Comment by jcmackie** [comment]
Hi,

I have the same problem as @edmachine.
After a bit of searching, it looks like it's caused by this line:
https://github.com/jdauphant/ansible-role-nginx/blob/master/tasks/configuration.yml#L66

Specifically, the `loop` keyword doesn't look like it's supported until Ansible 2.5:
https://docs.ansible.com/ansible/2.5/user_guide/playbooks_loops.html
> Before 2.5 Ansible mainly used the with_<lookup> keywords to create loops, the loop keyword is basically analogous to with_list.

I have no idea what "mainly" means in this context. But without going into the code for those versions, I suspect this is going to be as close as you get to a 'added in version' change doc.

I think while we wait for this to be patched, it's probably just a good idea to pin to the last version.

Cheers,
James

**Comment by jdauphant** [comment]
@edelans @jcmackie It's have been fixed by @q2digger : thanks for the report !

**Comment by edelans** [comment]
thks for the follow up @jdauphant =)

**Pull request merged**
