### PR TITLE
Allow using nginx official repo for RHEL/CentOS

### PR DESCRIPTION
**Pull request by victorluft**

### CODE REVIEW

**Comment by jdauphant** [comment]
Hi @victorluft,

Thanks for the pull request.
It's very good, I just have one remark : 
- I think that "enablerepo=nginx," in the yum task should be conditioned by the variable "nginx_official_repo"

**Comment by victorluft** [comment]
Ahh, yup, you're right, let me fix that.

**Comment by victorluft** [comment]
Fixed & squashed.

**Comment by jdauphant** [comment]
Ok thanks.
If nginx_official_repo == False :
Can you confirm that the first "," in "enablerepo=,epel,base" isn't a problem ?

**Comment by victorluft** [comment]
Well, it ran, but fixed just in case. :smile:

**Comment by jdauphant** [comment]
Ok I have merged

**Comment by victorluft** [comment]
Thanks very much.

**Pull request merged**
