### PR TITLE
fixing systemd issue when daemon is set to on

### PR DESCRIPTION
**Pull request by deimosfr**
Hi,

This role is not working with systemd installed on the machine. Here is a fix.

Can you please merge it.

Thanks

### CODE REVIEW

**Comment by jdauphant** [comment]
Hi @deimosfr ,

Thanks for the pull request, we can do more simple and generic.
Normally this should work in templates/nginx.conf.j2 :
```
{% if nginx_daemon_mode == "off" %}
daemon off;
{% endif %}
```
Notes : by default for nginx is "daemon on".

Best regards,
Julien

**Comment by deimosfr** [comment]
Hi,

Thanks for your answer. In fact no, it won't work. Because as said in the #38 ticket, if you're using systemd, you can't declare twice the "daemon" parameter. It's rejected by nginx validator.

And if you're asking why twice, it's simply because "daemon" parameter is hard coded in the systemd script of Debian Jessie :-/. So in fact, it's not possible to disable it if you're running systemd with its default given configuration on Debian Jessie :-(.

However, this fix permit to make it work if you've set it to "on".

**Comment by jdauphant** [comment]
Yes I understand, I also read the ticket.
But :
- The variable "nginx_daemon_mode" is "on" by default on the role
   - in this case with my modification, the template doesn't declare "daemon on" in the configuration file (that should correct your problem)
- People that use "nginx_daemon_mode: off", use nginx differently even if they have systemd in their systems
- I am 99% sure that will work in your configuration

**Comment by deimosfr** [comment]
You're right, in my configuration it will work ! However, it's a shame that we could not better cover the "off" case.

**Comment by deimosfr** [comment]
Just updated with your suggestion. Can you please merge and make a new release ?

Thanks

**Comment by jdauphant** [comment]
Ok thanks @deimosfr , I just merge. I juste make the release /v1.2.1.
Also, it's not a shame for me :
If you use the "daemon off", you have to now what you do and in general it doesn't not involve an init system.

**Comment by deimosfr** [comment]
ok make sense. Thanks a lot :-)

**Comment by deimosfr** [comment]
Can you please update ansible galaxy as well. Thanks

**Comment by jdauphant** [comment]
It's update on ansible galaxy.

**Comment by deimosfr** [comment]
Thanks it works !

**Pull request merged**
